# 元数据信息
meta:
  name: "sm8650"
  author: "yuki"
  configVersion: 20
  loglevel: "INFO"

# 主要功能开关
function:
  AffinitySetter: true
  CpuIdleScaling_Governor: false
  EasScheduler: true
  cpuset: true
  LoadBalancing: true
  EnableFeas: false
  AdjIOScheduler: true
  AppLaunchBoost: true

# App启动加速设置
AppLaunchBoostSettings:
  FreqMulti: 1.2    # 频率提升倍率 (1.2 表示提升20%)
  BoostRateMs: 200  # 持续时间 (毫秒)

# 核心分配设置
CoreAllocation:
  cpusetCore: "2-7"
  cpuctlUclampBoostMin: "0"
  cpuctlUclampBoostMax: "100"

# 核心框架路径
CoreFramework:
  SmallCorePath: 0
  MediumCorePath: 2
  BigCorePath: 5
  SuperBigCorePath: 7

# IO 调度器设置
IO_Settings:
  Scheduler: ""
  IO_optimization: true

# EAS 调度器参数 
EasSchedulerValue:
  sched_min_granularity_ns: "2000000"
  sched_nr_migrate: "30"
  sched_wakeup_granularity_ns: "3200000"
  sched_schedstats: "0"

# CPU 空闲设置
CpuIdle:
  current_governor: ""

# Cpuset 分组
Cpuset:
  top_app: "0-7"
  foreground: "0-7"
  restricted: "0-5"
  system_background: "1-2"
  background: "0-2"

Bus_dcvs_Path:
  CPUllccminPath: ""
  CPUllccmaxPath: ""
  CPUddrminPath: ""
  CPUddrmaxPath: ""

#调速器参数（path可加） 
pGovPath:
  schedutil:
    path1: ""
    path2: ""
    path3: ""
  walt:
    path1: ""
    path2: ""
    path3: ""

# --- 性能模式 ---

# 省电模式
powersave:
  # 调速器
  Governor: 
    global: "schedutil"
    SmallCore: ""
    MediumCore: "" 
    BigCore: ""
    SuperBigCore: ""   
  # 频率
  Freq:
    SmallCoreMinFreq: "min"
    SmallCoreMaxFreq: 1500000
    MediumCoreMinFreq: "min"
    MediumCoreMaxFreq: 1800000
    BigCoreMinFreq: "min"
    BigCoreMaxFreq: 1700000
    SuperBigCoreMinFreq: "min"
    SuperBigCoreMaxFreq: 1700000
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "0"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "70"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""

  # 其他设置
  Other:
    ufsClkGate: false

# 均衡模式
balance:
  # 调速器
  Governor: 
    global: "walt"
    SmallCore: ""
    MediumCore: "" 
    BigCore: ""
    SuperBigCore: ""   
  # 频率
  Freq:
    SmallCoreMinFreq: 600000
    SmallCoreMaxFreq: 1800000
    MediumCoreMinFreq: 800000
    MediumCoreMaxFreq: 2200000
    BigCoreMinFreq: 800000
    BigCoreMaxFreq: 2200000
    SuperBigCoreMinFreq: 1000000
    SuperBigCoreMaxFreq: 2300000
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "0"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "70"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
  # 其他设置
  Other:
    ufsClkGate: false

# 性能模式
performance:
  # 调速器
  Governor: 
    global: "schedutil"
    SmallCore: ""
    MediumCore: "" 
    BigCore: ""
    SuperBigCore: ""   
  # 频率
  Freq:
    SmallCoreMinFreq: 1500000
    SmallCoreMaxFreq: 2400000
    MediumCoreMinFreq: 1800000
    MediumCoreMaxFreq: 2600000
    BigCoreMinFreq: 1900000
    BigCoreMaxFreq: 2600000
    SuperBigCoreMinFreq: 2200000
    SuperBigCoreMaxFreq: 3200000  
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "80"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"  
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
  # 其他设置
  Other:
    ufsClkGate: false

# 极速模式
fast:
  # 调速器
  Governor: 
    global: "walt"
    SmallCore: ""
    MediumCore: "" 
    BigCore: ""
    SuperBigCore: ""    
  # 频率
  Freq:
    SmallCoreMinFreq: 1500000
    SmallCoreMaxFreq: "max"
    MediumCoreMinFreq: 1800000
    MediumCoreMaxFreq: "max"
    BigCoreMinFreq: 1900000
    BigCoreMaxFreq: "max"
    SuperBigCoreMinFreq: 2200000
    SuperBigCoreMaxFreq: "max"  
  # 频率限制
  Uclamp:
    UclampTopAppMin: "10"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "80"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"  
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
        BigCore: ""
        SuperBigCore: ""
  # 其他设置
  Other:
    ufsClkGate: true