# 元数据信息
meta:
  name: "sm8850"
  author: "yuki"
  language: "en"
  loglevel: "INFO"

# 主要功能开关
function:
  AffinitySetter: false
  CpuIdleScalingGovernor: false
  EasScheduler: true
  cpuset: true
  LoadBalancing: true
  EnableFeas: false
  AdjIOScheduler: true
  AppLaunchBoost: true

# App启动加速设置
AppLaunchBoostSettings:
  FreqMulti: 1.2    # 频率提升倍率
  BoostRateMs: 600  # 持续时间

# 核心分配设置
CoreAllocation:
  CpuSetCore: "0-7"

# 核心框架路径
CoreFramework:
  SmallCorePath: 0
  MediumCorePath: 6 
  BigCorePath: -1
  SuperBigCorePath: -1

# IO 调度器设置
IO_Settings:
  Scheduler: ""
  IO_optimization: true

# CFS 调度器参数
CompletelyFairSchedulerValue:
  sched_child_runs_first: ""
  sched_rt_period_us: ""
  sched_rt_runtime_us: ""

# CPU 空闲设置
CpuIdle:
  current_governor: ""

# Cpuset 分组
Cpuset:
  top_app: "0-7"
  foreground: "0-7"
  restricted: "0-5"
  system_background: "0-3"
  background: "0-3"

Bus_dcvs_Path:
  CPUllccminPath: ""
  CPUllccmaxPath: ""
  CPUddrminPath: ""
  CPUddrmaxPath: ""

# 调速器参数 
pGovPath:
  schedutil:
    path1: ""
    path2: ""
    path3: ""
  walt:
    path1: ""
    path2: ""
    path3: ""

# --- 性能模式 ---

# 省电模式
powersave:
  # 调速器
  Governor:
    Global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  Freq:
    SmallCoreMinFreq: 0
    SmallCoreMaxFreq: 1555200 
    MediumCoreMinFreq: 0
    MediumCoreMaxFreq: 1632000 
    BigCoreMinFreq: 0
    BigCoreMaxFreq: 0
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0
  Uclamp:
    UclampTopAppMin: "5"
    UclampTopAppMax: "60"
    UclampTopApplatency_sensitive: "0"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "40"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "20"
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
  Other:
    ufsClkGate: true

# 均衡模式
balance:
  # 调速器
  Governor:
    Global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 0
    SmallCoreMaxFreq: 2611200
    MediumCoreMinFreq: 0
    MediumCoreMaxFreq: 2880000
    BigCoreMinFreq: 0
    BigCoreMaxFreq: 0
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0
  Uclamp:
    UclampTopAppMin: "7"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "65"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "45"
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
  Other:
    ufsClkGate: true

# 性能模式
performance:
  # 调速器
  Governor:
    Global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 0
    SmallCoreMaxFreq: 3398400  # 约 3.40GHz
    MediumCoreMinFreq: 0
    MediumCoreMaxFreq: 3974400  # 约 3.97GHz
    BigCoreMinFreq: 0
    BigCoreMaxFreq: 0
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0
  # 频率限制
  Uclamp:
    UclampTopAppMin: "10"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "80"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
  Other:
    ufsClkGate: true

# 极速模式
fast:
  # 调速器
  Governor:
    Global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 0
    SmallCoreMaxFreq: "max"
    MediumCoreMinFreq: 0
    MediumCoreMaxFreq: "max"
    BigCoreMinFreq: 0
    BigCoreMaxFreq: 0
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0
  # 频率限制
  Uclamp:
    UclampTopAppMin: "10"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "100"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "60"
  #总线频率
  Bus_dcvs:
    CPUllccmin: ""
    CPUllccmax: ""
    CPUddrmin: ""
    CPUddrmax: ""
  #调速器参数值
  Govsets:
    schedutil:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
    walt:
      path1: 
        SmallCore: ""
        MediumCore: ""
      path2: 
        SmallCore: ""
        MediumCore: ""
      path3: 
        SmallCore: ""
        MediumCore: ""
  Other:
    ufsClkGate: true